/* 
 * File:   main.cpp
 * Author: Megan Varner 
 * Created on July 13, 2014, 9:03 AM
 * Guess the number in my head game
 */

//Libraries
#include <iostream>
#include <cstdlib>
#include <time.h>
#include <string> 

using namespace std;

int main(int argc, char** argv)
{
    bool play_again = true;
    while(play_again == true)
    {
      srand(time(NULL));  
      int number =  rand() % 50 + 1; 
      //stores random number between 1-50
      bool is_guess_correct = false; 
  	  int input_number;
  	  int attempts_count = 1; 
          // number of attempts player has made
    
      //loops until player enters correct number
  	  while(is_guess_correct == false) 
  	  {
  		    if(attempts_count == 1) 
  		    {
  				  cout << "Enter Number 1-50: ";
  		    }
  		    else
  		    {
    				cout << "Enter Number Again : ";
              		    }
  		    cin >> input_number;
                        if(input_number == number)
  		    {
                     //Player wins!
    				 cout << "Congratulation! You have guessed the correct number in " << attempts_count << " attempts" << endl;
    				 is_guess_correct = true;
                                 //stops loop if true
  		    }
  		    else
  		    {
            //Player needs to keep guessing
    				 attempts_count++; // attempts
    				 if(input_number < number) //if user entered number is less than random number 
    				 {
    				   cout << "Entered number is small than then number to be guess." << endl;
    				 }
                        }
                    		cout << "Enter Number Again : "; //this line will be printed on all attempts except first one
  		    }
  		    cin >> input_number;
          
        //Cross references guess and random number
  		    if(input_number == number)
  		    {
            //We are here because user entered same number as generated by computer
    				 cout << "Congratulation! You have guessed the correct number in " << attempts_count << " attempts" << endl;
    				 is_guess_correct = true;
                                 //stops loop if true
  		    }
  		    else
  		    {
            //guess wrong
    				 attempts_count++; // attempts
    				 if(input_number < number) 
                       //Player entered number less than random number 
    				 {
    cout << "Entered number is smaller than the number to be guess." << endl;
    				 }
    				else  
                           //Player entered number greater than random number
    				 {
  cout << "Entered number is greater than the number to be guess." << endl;
    				 }
  		    }
  	  }
      //Play again?
      string choice;
      cout << "Press P to play again or any other key to terminate : ";
      cin >> choice;
      //player chooses any other key than P/p quits
      if(choice != "P" && choice != "p")
      {
        play_again = false;
      }
	
      //Exit Stage right
   return 0; 
}