/* 
 * File:   main.cpp
 * Author: Megan Varner
 * Created on June 28, 2014, 5:13 PM
 * amount of income generated by ticket sale
 */

#include <iostream>

        
using namespace std;
 

int main(int argc, char** argv) 
{
    double class_A, class_B, class_C, income_in, classa_mon, classb_mon,
            classc_mon;
    
    cout <<"Press enter after every number you type.\n";
    cout <<"How many Class A seats were sold?\n";
    cin >> class_A;
    
    cout <<"How many Class B seats were sold?\n";
    cin >> class_B;
    
    cout <<"How many Class C seats were sold?\n";
    cin >> class_C;
    
    classa_mon = class_A * 15; //Rate A
    //Income for class A tickets
    
    classb_mon = class_B * 12; //Rate B
    //Income for class B tickets
    
    classc_mon = class_C * 9; //Rate C
    //Income for class C tickets
    
    income_in = classa_mon + classb_mon + classc_mon;
    //income generated by ticket sales of all classes
    
    cout << "If "<<class_A<<" seats were sold for Class A,\n";
    cout <<class_B<<" seats were sold for Class B,\n";
    cout <<"and "<<class_C<< " seats were sold for Class C\n";
    
    cout.setf(ios::fixed);
    cout.precision(2);
    //sets decimal precision
    
    cout <<"then, the income generated is $"<<income_in;
    cout <<" through ticket sales.\n";
    return 0;
}

